// Shared student database — batch + division aware
const students = [

    // ===================== 61st BATCH =====================

    // --- 61st EA (Division A) ---
    { name: "Hitesh",                      pass: "2685", batch: "61st", division: "EA" },
    { name: "Deva",                        pass: "1371", batch: "61st", division: "EA" },
    { name: "Tejas Ganpat Padwal",         pass: "3311", batch: "61st", division: "EA" },
    { name: "Tanuja Suresh Shirke",         pass: "3346", batch: "61st", division: "EA" },
    { name: "Bhushan Gurunath Vishe",       pass: "3341", batch: "61st", division: "EA" },
    { name: "Yash Ankush Kumawat",          pass: "3294", batch: "61st", division: "EA" },
    { name: "Yadnyesh Prakash Partole",     pass: "3313", batch: "61st", division: "EA" },
    { name: "Kunal Pundalik Mahajan",       pass: "3301", batch: "61st", division: "EA" },
    { name: "Shriraj Nitin Wadkar",         pass: "3344", batch: "61st", division: "EA" },
    { name: "Dimpal Subhash Rasal",         pass: "3322", batch: "61st", division: "EA" },
    { name: "Shreya Sharad Dabhade",        pass: "3263", batch: "61st", division: "EA" },
    { name: "Kasturi Kiran Shingate",       pass: "3329", batch: "61st", division: "EA" },
    { name: "Adil Dawood Khan",             pass: "3288", batch: "61st", division: "EA" },
    { name: "Jitesh Ganesh Rane",           pass: "3320", batch: "61st", division: "EA" },
    { name: "Parth Gajanan Kondilkar",      pass: "3292", batch: "61st", division: "EA" },
    { name: "Nikhil Pradip Gadage",         pass: "3272", batch: "61st", division: "EA" },
    { name: "Saurabh Shivaji Bhoir",        pass: "3252", batch: "61st", division: "EA" },
    { name: "Swapnil Jotiram Jambhale",     pass: "3281", batch: "61st", division: "EA" },
    { name: "Harsh Ganesh Patil",           pass: "3314", batch: "61st", division: "EA" },
    { name: "Soham Mahendra Chaudhari",     pass: "3261", batch: "61st", division: "EA" },
    { name: "Payal Tatya Suryavanshi",      pass: "3334", batch: "61st", division: "EA" },
    { name: "Manas Sunil Lad",              pass: "3296", batch: "61st", division: "EA" },
    { name: "Daksh Prabhakar Sonawane",     pass: "3330", batch: "61st", division: "EA" },
    { name: "Viraj Dhanaji Malik",          pass: "3302", batch: "61st", division: "EA" },
    { name: "Sujit Dinesh Magar",           pass: "3299", batch: "61st", division: "EA" },
    { name: "Samadhan Sitaram Suryavanshi", pass: "3335", batch: "61st", division: "EA" },
    { name: "Pramita Gautam Vavhal",        pass: "3340", batch: "61st", division: "EA" },
    { name: "Ruchita Pandurang Farde",      pass: "3271", batch: "61st", division: "EA" },
    { name: "Dimpal Rasal",                 pass: "3321", batch: "61st", division: "EA" },
    { name: "Tanuja Walimbe",               pass: "3346", batch: "61st", division: "EA" },
    { name: "Sankit Kahar",                 pass: "3284", batch: "61st", division: "EA" },
    { name: "Nayan Kondilkar",              pass: "3291", batch: "61st", division: "EA" },
    { name: "Om Vishe",                     pass: "3342", batch: "61st", division: "EA" },

    // --- 61st EB (Division B) ---
    { name: "Hitesh",                      pass: "2685", batch: "61st", division: "EB" },
    { name: "Deva",                        pass: "1371", batch: "61st", division: "EB" },
    { name: "Jayshree Vasant Dongare",      pass: "3352", batch: "61st", division: "EB" },
    { name: "Sayali Mahadev Gondhali",      pass: "3276", batch: "61st", division: "EB" },
    { name: "Kartiki Kadam",                pass: "3351", batch: "61st", division: "EB" },
    { name: "Nishant Bharat Jadhav",        pass: "3289", batch: "61st", division: "EB" },
    { name: "Ashish Ganesh Pawar",          pass: "3343", batch: "61st", division: "EB" },
    { name: "Teju Deepak Joshi",            pass: "3316", batch: "61st", division: "EB" },
    { name: "Paras Bhagwan Rane",           pass: "3251", batch: "61st", division: "EB" },
    { name: "Aryan Sameer Shaikh",          pass: "3257", batch: "61st", division: "EB" },
    { name: "Dhiraj Anil Pawar",            pass: "3317", batch: "61st", division: "EB" },
    { name: "Vighnesh Suryakant Patil",     pass: "3306", batch: "61st", division: "EB" },
    { name: "Renuka Kailas Jaybhaye",       pass: "3283", batch: "61st", division: "EB" },
    { name: "Indra Arun Redekar",           pass: "3324", batch: "61st", division: "EB" },
    { name: "Samruddhi Mahadev Patil",      pass: "3270", batch: "61st", division: "EB" },
    { name: "Khushali Sainath Jadhav",      pass: "3332", batch: "61st", division: "EB" },
    { name: "Shivani Sharad Khairnar",      pass: "3287", batch: "61st", division: "EB" },
    { name: "Nayan Ashok Chaudhari",        pass: "3258", batch: "61st", division: "EB" },
    { name: "Raj Ramkrit Yadav",            pass: "3295", batch: "61st", division: "EB" },
    { name: "Anagha Hanumant Raul",         pass: "3323", batch: "61st", division: "EB" },
    { name: "Shravan Wadkar",               pass: "3345", batch: "61st", division: "EB" },
    { name: "Siddhesh Sopan Patil",         pass: "3336", batch: "61st", division: "EB" },
    { name: "Aryan Ganpat More",            pass: "3303", batch: "61st", division: "EB" },
    { name: "Tanmay Mahendra Gupta",        pass: "3293", batch: "61st", division: "EB" },
    { name: "Sarthak Dattatray Pawar",      pass: "3246", batch: "61st", division: "EB" },
    { name: "Yash Sharad Vekhande",         pass: "3348", batch: "61st", division: "EB" },
    { name: "Rishabh Santosh Patil",        pass: "3333", batch: "61st", division: "EB" },
    { name: "Aryan Anil Shinde",            pass: "3328", batch: "61st", division: "EB" },
    { name: "Nikhil Pradip Jadhav",         pass: "3285", batch: "61st", division: "EB" },
    { name: "Purva Panchal",                pass: "3356", batch: "61st", division: "EB" },
    { name: "Shivam Thakur",                pass: "3337", batch: "61st", division: "EB" },

    // ===================== 62nd BATCH =====================

    // --- 62nd EA (Division A) ---
    { name: "Hitesh",                      pass: "2685", batch: "62nd", division: "EA" },
    { name: "Deva",                        pass: "1371", batch: "62nd", division: "EA" },
    { name: "Yashraj Dinesh Patil",         pass: "3472", batch: "62nd", division: "EA" },
    { name: "Velvin Vishal Gupta",           pass: "3466", batch: "62nd", division: "EA" },
    { name: "Jagruti Madhukar Patil",        pass: "3402", batch: "62nd", division: "EA" },
    { name: "Harshad Keshav Bajage",         pass: "3398", batch: "62nd", division: "EA" },
    { name: "Jaykumar Vishe",                pass: "3405", batch: "62nd", division: "EA" },
    { name: "Darshan Bhoir",                 pass: "3386", batch: "62nd", division: "EA" },
    { name: "Rajesh Balkrishna Patil",       pass: "3429", batch: "62nd", division: "EA" },
    { name: "Parth Ghadage",                 pass: "3419", batch: "62nd", division: "EA" },
    { name: "Tejaswini Gawali",              pass: "3458", batch: "62nd", division: "EA" },
    { name: "Prathamesh Shinde",             pass: "3426", batch: "62nd", division: "EA" },
    { name: "Vedika Sangle",                 pass: "3465", batch: "62nd", division: "EA" },
    { name: "Sanskruti Sanjay Kamble",       pass: "3439", batch: "62nd", division: "EA" },
    { name: "Niyati Kamlesh Patil",          pass: "3417", batch: "62nd", division: "EA" },
    { name: "Pranjal Howal",                 pass: "3423", batch: "62nd", division: "EA" },
    { name: "Bhavesh Bhoir",                 pass: "3380", batch: "62nd", division: "EA" },
    { name: "Karan Dalvi",                   pass: "3407", batch: "62nd", division: "EA" },
    { name: "Vedant Vishwas Patil",          pass: "3464", batch: "62nd", division: "EA" },
    { name: "Lalit Pruthviraj Patil",        pass: "3413", batch: "62nd", division: "EA" },
    { name: "Pradnya Sutar",                 pass: "3422", batch: "62nd", division: "EA" },
    { name: "Samiksha Ravindra Kasare",      pass: "3436", batch: "62nd", division: "EA" },
    { name: "Sayali Subhash Kondvilkar",     pass: "3443", batch: "62nd", division: "EA" },
    { name: "Kirti Kishor Patil",            pass: "3474", batch: "62nd", division: "EA" },
    { name: "Antara Vishwas Patil",          pass: "3376", batch: "62nd", division: "EA" },
    { name: "Vedika Vishwas Egade",          pass: "3478", batch: "62nd", division: "EA" },
    { name: "Samiksha Suresh Vaidya",        pass: "3435", batch: "62nd", division: "EA" },
    { name: "Sarvesh Vijay Patil",           pass: "3442", batch: "62nd", division: "EA" },
    { name: "Dhammapal Bhimsen Gaikwad",     pass: "3388", batch: "62nd", division: "EA" },
    { name: "Yadnya Mahesh Patil",           pass: "3468", batch: "62nd", division: "EA" },
    { name: "Sushant Nandkumar Patil",       pass: "3453", batch: "62nd", division: "EA" },
    { name: "Ruksana Bashir Shaikh",         pass: "3431", batch: "62nd", division: "EA" },
    { name: "Prathmesh Sunil Patil",         pass: "3427", batch: "62nd", division: "EA" },
    { name: "Vaibhavi Rahul Tupe",           pass: "3460", batch: "62nd", division: "EA" },
    { name: "Dinesh Mahesh Patil",           pass: "3390", batch: "62nd", division: "EA" },
    { name: "Chirag Viraj Patil",            pass: "3385", batch: "62nd", division: "EA" },

    // --- 62nd EB (Division B) ---
    { name: "Hitesh",                      pass: "2685", batch: "62nd", division: "EB" },
    { name: "Deva",                        pass: "1371", batch: "62nd", division: "EB" },
    { name: "Gayatri Balakrishna Bhoir",     pass: "3396", batch: "62nd", division: "EB" },
    { name: "Vaishnavi Sitaram Gaikwad",     pass: "3461", batch: "62nd", division: "EB" },
    { name: "Kunal Narayan Padwal",          pass: "3412", batch: "62nd", division: "EB" },
    { name: "Bhagyashree Sachin Ghude",      pass: "3379", batch: "62nd", division: "EB" },
    { name: "Prashant Vinayak Bangar",       pass: "3424", batch: "62nd", division: "EB" },
    { name: "Siddhi Santosh Wadavale",       pass: "3448", batch: "62nd", division: "EB" },
    { name: "Durvesh Kiran Ambekar",         pass: "3392", batch: "62nd", division: "EB" },
    { name: "Sanika Mahendra Posate",        pass: "3437", batch: "62nd", division: "EB" },
    { name: "Omkar Ashok Vishe",             pass: "3418", batch: "62nd", division: "EB" },
    { name: "Sujata Ravindra Shirke",        pass: "3450", batch: "62nd", division: "EB" },
    { name: "Kaushik Vikas Chaudhari",       pass: "3410", batch: "62nd", division: "EB" },
    { name: "Riya Sachin Gangawane",         pass: "3430", batch: "62nd", division: "EB" },
    { name: "Durvesh Liladhar Madhavi",      pass: "3393", batch: "62nd", division: "EB" },
    { name: "Mayuresh Mangesh Bane",         pass: "3415", batch: "62nd", division: "EB" },
    { name: "Jayesh Padmakar Vekhande",      pass: "3404", batch: "62nd", division: "EB" },
    { name: "Shlok Sunil Patil",             pass: "3445", batch: "62nd", division: "EB" },
    { name: "Harsh Vasant Gawale",           pass: "3397", batch: "62nd", division: "EB" },
    { name: "Shreya Sandeep Mane",           pass: "3446", batch: "62nd", division: "EB" },
    { name: "Sarthak Santosh Pawar",         pass: "3441", batch: "62nd", division: "EB" },
    { name: "Tanuja Shirke",                 pass: "3457", batch: "62nd", division: "EB" },
    { name: "Sourya Mahendra Patle",         pass: "3449", batch: "62nd", division: "EB" },
    { name: "Nikita Balu Harad",             pass: "3479", batch: "62nd", division: "EB" },
    { name: "Prathmesh Nitin Shinde",        pass: "3425", batch: "62nd", division: "EB" },
    { name: "Vedant Nana Suroshi",           pass: "3463", batch: "62nd", division: "EB" },
    { name: "Unnati Rajendra Suroshe",       pass: "3459", batch: "62nd", division: "EB" },
    { name: "Bhavika Anil Late",             pass: "3382", batch: "62nd", division: "EB" },
    { name: "Dipti Yashwant Gund",           pass: "3391", batch: "62nd", division: "EB" },
    { name: "Bhargavi Somnath Bhegade",      pass: "3476", batch: "62nd", division: "EB" },
    { name: "Shruti Haresh Gharat",          pass: "3477", batch: "62nd", division: "EB" },
    { name: "Harshada Rane",                 pass: "3399", batch: "62nd", division: "EB" },
    { name: "Lavanya Bharat Vishe",          pass: "3414", batch: "62nd", division: "EB" },
    { name: "Sakshi Santosh Desale",         pass: "3434", batch: "62nd", division: "EB" },
    { name: "Pratibha Bangal",               pass: "3420", batch: "62nd", division: "EB" },
    { name: "Sanskruti Patange",             pass: "3428", batch: "62nd", division: "EB" },
    { name: "Jayshree Vasant Kamble",        pass: "3352", batch: "62nd", division: "EB" },
];
